# Generated by Django 3.1.6 on 2021-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
